name: Main workflow

on: [push]

jobs:
  test_and_build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup
        run: |
          npm install -g esy@latest
          npm install -g cross-env # for windows :/

      - name: install
        run: |
          esy install
          cd tests && npm install && cd ../

      - name: build
        run: |
          esy build

      - name: test
        run: |
          cd tests && npm run test && cd ../
          mv _build/default/src/bucklescript_bin/bin.exe graphql_ppx-${{ matrix.os }}.exe
        env:
          CI: true

      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: graphql_ppx-${{ matrix.os }}.exe
          path: graphql_ppx-${{ matrix.os }}.exe

  publish:
    needs: test_and_build
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: graphql_ppx-ubuntu-latest.exe
          path: graphql_ppx-linux-x64.exe

      - name: Download macOS artifacts
        uses: actions/download-artifact@master
        with:
          name: graphql_ppx-macOS-latest.exe
          path: graphql_ppx-darwin-x64.exe

      - name: Download windows artifacts
        uses: actions/download-artifact@master
        with:
          name: graphql_ppx-windows-latest.exe
          path: graphql_ppx-win-x64.exe

      - name: Move artifacts
        run: |
          mkdir -p bin
          mv graphql_ppx-win-x64.exe bin/graphql_ppx-win-x64.exe
          mv graphql_ppx-darwin-x64.exe bin/graphql_ppx-darwin-x64.exe
          mv graphql_ppx-linux-x64.exe bin/graphql_ppx-linux-x64.exe

      - name: Publish
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish
